version: "1.0"
server:
  name: "Fuseki server simple"
services:
  - name: "ds"
    endpoints:
      - operation: query
        settings:
      - name: "upload"
        operation: upload
    database:  "abac-tdb2-db"

databases:
  - name: "abac-tdb2-db"
    dbtype: ABAC
    dataset: "dataset-under"
    attributes: "abac/attribute-store.ttl"
    labels-store: "target/labels"

  - name: "dataset-under"
    dbtype: TDB2
    location: "target/test-abac-DB"